// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.25.1

import { Writer, Reader } from "as-proto/assembly";
import { Transaction } from "./Transaction";

export class Block {
  static encode(message: Block, writer: Writer): void {
    writer.uint32(8);
    writer.uint64(message.timestamp);

    writer.uint32(16);
    writer.uint64(message.block);

    const txs = message.txs;
    for (let i: i32 = 0; i < txs.length; ++i) {
      writer.uint32(26);
      writer.fork();
      Transaction.encode(txs[i], writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): Block {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new Block();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.timestamp = reader.uint64();
          break;

        case 2:
          message.block = reader.uint64();
          break;

        case 3:
          message.txs.push(Transaction.decode(reader, reader.uint32()));
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  timestamp: u64;
  block: u64;
  txs: Array<Transaction>;

  constructor(
    timestamp: u64 = 0,
    block: u64 = 0,
    txs: Array<Transaction> = []
  ) {
    this.timestamp = timestamp;
    this.block = block;
    this.txs = txs;
  }
}
