// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.25.1

import { Writer, Reader } from "as-proto/assembly";
import { Ordinals } from "./Ordinals";

export class OrdinalsAssignment {
  static encode(message: OrdinalsAssignment, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.utxo);

    const ordinals = message.ordinals;
    if (ordinals !== null) {
      writer.uint32(18);
      writer.fork();
      Ordinals.encode(ordinals, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): OrdinalsAssignment {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new OrdinalsAssignment();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.utxo = reader.string();
          break;

        case 2:
          message.ordinals = Ordinals.decode(reader, reader.uint32());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  utxo: string;
  ordinals: Ordinals | null;

  constructor(utxo: string = "", ordinals: Ordinals | null = null) {
    this.utxo = utxo;
    this.ordinals = ordinals;
  }
}
